ALTER TABLE deep_analyses
    ADD COLUMN claimed_at TIMESTAMP NULL AFTER status,
    ADD COLUMN worker_id VARCHAR(64) NULL AFTER claimed_at,
    ADD COLUMN attempt_count INT NOT NULL DEFAULT 0 AFTER worker_id,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
