/* Phase 1 intelligence system — fixture data
   Sources/IDs/fields match data-model.md + source-catalog.md verbatim. */

export const FIXTURES = (() => {
  const now = new Date('2026-05-26T08:14:00+08:00');
  // Keep fixture timestamps relative to one anchor so the UI reads consistently.
  const iso = (d) => d.toISOString();
  const ago = (mins) => iso(new Date(now.getTime() - mins * 60000));
  // Mirror the API's cross-source occurrence shape used by item drawers and digests.
  const seen = (source_id, mins, url = null) => ({ source_id, url, seen_at: ago(mins) });

  /* ---------- sources ---------- */
  const sources = [
    {
      id: 'security_nvd_cve', name: 'NVD CVE Feed', domain: 'security', type: 'api',
      url: 'https://services.nvd.nist.gov/rest/json/cves/2.0',
      authority: 'official', status: 'approved', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(38), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_api', is_active: true, today_items: 18,
      spark: [12, 8, 14, 11, 22, 17, 9, 13, 18, 21, 14, 18],
    },
    {
      id: 'security_github_advisories', name: 'GitHub Security Advisories', domain: 'security', type: 'github_api',
      url: 'https://api.github.com/advisories',
      authority: 'official', status: 'approved', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(38), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_github', is_active: true, today_items: 7,
      spark: [4, 6, 3, 8, 5, 7, 4, 9, 6, 5, 8, 7],
    },
    {
      id: 'security_portswigger', name: 'PortSwigger Research', domain: 'security', type: 'rss',
      url: 'https://portswigger.net/research/rss',
      authority: 'authoritative', status: 'trial', health: 'degraded', consecutive_failures: 2,
      last_fetch_at: ago(38), last_fetch_status: 'source_timeout',
      fetch_strategy: 'l1_rss', is_active: true, today_items: 0,
      spark: [1, 0, 2, 1, 0, 1, 2, 0, 1, 0, 0, 0],
    },
    {
      id: 'security_project_zero', name: 'Project Zero Blog', domain: 'security', type: 'rss',
      url: 'https://googleprojectzero.blogspot.com/feeds/posts/default',
      authority: 'authoritative', status: 'trial', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(38), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_rss', is_active: true, today_items: 1,
      spark: [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    },
    {
      id: 'security_exploitdb', name: 'Exploit-DB', domain: 'security', type: 'rss',
      url: 'https://www.exploit-db.com/rss.xml',
      authority: 'authoritative', status: 'trial', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(38), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_rss', is_active: true, today_items: 5,
      spark: [3, 7, 4, 5, 6, 3, 4, 8, 5, 6, 4, 5],
    },
    {
      id: 'security_sechub', name: 'SecHub Internal', domain: 'security', type: 'internal_api',
      url: 'http://127.0.0.1:18210/api/feed',
      authority: 'authoritative', status: 'candidate', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(37), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_api', is_active: true, today_items: 4,
      spark: [2, 3, 5, 4, 3, 2, 4, 5, 3, 4, 2, 4],
    },
    {
      id: 'ai_aihot', name: 'aihot Internal', domain: 'ai', type: 'internal_api',
      url: 'http://127.0.0.1:18220/api/feed',
      authority: 'authoritative', status: 'candidate', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(36), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_api', is_active: true, today_items: 12,
      spark: [8, 10, 6, 9, 12, 11, 8, 14, 10, 9, 11, 12],
    },
    {
      id: 'ai_hackernews', name: 'Hacker News (filtered)', domain: 'ai', type: 'api',
      url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
      authority: 'authoritative', status: 'approved', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(36), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_api', is_active: true, today_items: 9,
      spark: [5, 8, 4, 7, 9, 6, 11, 8, 5, 9, 7, 9],
    },
    {
      id: 'ai_arxiv', name: 'arXiv cs.AI + cs.CR', domain: 'ai', type: 'rss',
      url: 'https://export.arxiv.org/rss/cs.AI+cs.CR',
      authority: 'official', status: 'trial', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(36), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_rss', is_active: true, today_items: 6,
      spark: [4, 5, 3, 7, 6, 4, 8, 5, 7, 6, 4, 6],
    },
    {
      id: 'ai_openai_blog', name: 'OpenAI Blog', domain: 'ai', type: 'rss',
      url: 'https://openai.com/news/rss.xml',
      authority: 'official', status: 'trial', health: 'good', consecutive_failures: 0,
      last_fetch_at: ago(36), last_fetch_status: 'succeeded',
      fetch_strategy: 'l1_rss', is_active: true, today_items: 1,
      spark: [0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1],
    },
  ];

  /* ---------- items ---------- */
  const items = [
    {
      id: 'security_nvd_cve:CVE-2026-31415', source_id: 'security_nvd_cve', domain: 'security',
      title: 'CVE-2026-31415: Out-of-bounds write in Linux kernel io_uring leading to local privilege escalation',
      canonical_url: 'https://nvd.nist.gov/vuln/detail/CVE-2026-31415',
      author: 'NVD', published_at: ago(180), fetched_at: ago(38),
      also_seen_in: [
        seen('security_github_advisories', 36, 'https://github.com/advisories/GHSA-7q4f-pgqx-h3vh'),
        seen('security_exploitdb', 34, 'https://www.exploit-db.com/exploits/52891'),
      ],
      category: 'vulnerability', tags: ['cve', 'linux', 'kernel', 'lpe', 'io_uring'],
      summary_zh: 'Linux 内核 io_uring 子系统存在越界写入漏洞，本地用户可触发以提权至 root。影响 6.6–6.12 LTS 系列，已有公开 PoC，建议立即升级。',
      insight_score: 92, credibility: 'high',
      confidence: 'confirmed',
      recommendation_reason: '官方 NVD 已收录、GHSA 同步发布、Exploit-DB 已上传可用 PoC，三源交叉确认。CVSS 7.8，无需用户交互且利用代码已公开。',
      trend_signal: 'emerging', action_suggestion: '立即在所有 Linux 主机上 patch 至 6.12.5+，对暴露 SSH 的实例优先处理；启用 audit 规则监控 io_uring 异常 syscall 序列。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
      cve_id: 'CVE-2026-31415', cvss: 7.8, cvss_vector: 'AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
    },
    {
      id: 'security_project_zero:1842', source_id: 'security_project_zero', domain: 'security',
      title: 'Bypassing Memory Tagging on Pixel 9 — A Year-long Look at MTE in the Wild',
      canonical_url: 'https://googleprojectzero.blogspot.com/2026/05/bypassing-mte-pixel9.html',
      author: 'Mark Brand', published_at: ago(420), fetched_at: ago(38),
      also_seen_in: [seen('ai_hackernews', 39, 'https://news.ycombinator.com/item?id=39812000')],
      category: 'research', tags: ['mte', 'android', 'memory-safety', 'arm'],
      summary_zh: 'Project Zero 团队对 Pixel 9 的 ARMv9 Memory Tagging Extension 进行了为期一年的攻防研究，发现 3 类绕过路径，涉及 tag-confusion、speculative leaks 与 user-pages 同源标签。',
      insight_score: 88, credibility: 'high',
      confidence: 'firm',
      recommendation_reason: 'Project Zero 官方深度技术研究，权威性极高；首次公开 MTE 在主流消费机上的实战分析。',
      trend_signal: 'growing', action_suggestion: '关注 Android 14 QPR3 是否将 sync-MTE 默认开启；后续 MTE 相关研究值得长期追踪。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
    },
    {
      id: 'security_github_advisories:GHSA-7q4f-pgqx-h3vh', source_id: 'security_github_advisories', domain: 'security',
      title: 'GHSA-7q4f-pgqx-h3vh: Remote code execution in next-auth v5 OAuth state validation',
      canonical_url: 'https://github.com/advisories/GHSA-7q4f-pgqx-h3vh',
      author: 'GitHub Security Lab', published_at: ago(240), fetched_at: ago(38),
      also_seen_in: [],
      category: 'vulnerability', tags: ['ghsa', 'next-auth', 'rce', 'oauth', 'javascript'],
      summary_zh: 'next-auth v5.0.0–5.0.7 在 OAuth 回调状态校验中存在反序列化漏洞，攻击者可构造恶意 state 参数实现 RCE。已发布修复版本 5.0.8。',
      insight_score: 84, credibility: 'high',
      confidence: 'firm',
      recommendation_reason: 'GitHub 官方安全公告，影响广泛使用的 Next.js 认证库，存量项目暴露面巨大。',
      trend_signal: 'emerging', action_suggestion: '在所有 Next.js 项目中检查 next-auth 版本，升级至 5.0.8。同时审计 OAuth 回调日志是否存在异常 state 长度记录。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
    },
    {
      id: 'security_exploitdb:52891', source_id: 'security_exploitdb', domain: 'security',
      title: 'Fortinet FortiManager 7.4.4 — Pre-auth Stack Buffer Overflow (Metasploit)',
      canonical_url: 'https://www.exploit-db.com/exploits/52891',
      author: 'h00die', published_at: ago(560), fetched_at: ago(38),
      also_seen_in: [seen('security_nvd_cve', 41, 'https://nvd.nist.gov/vuln/detail/CVE-2026-29812')],
      category: 'exploit', tags: ['fortinet', 'rce', 'msf', 'pre-auth'],
      summary_zh: 'Exploit-DB 上传 Fortinet FortiManager 7.4.4 之前版本的预认证栈溢出 Metasploit 模块，对应 CVE-2026-29812，公网可达设备风险高。',
      insight_score: 81, credibility: 'high',
      confidence: 'firm',
      recommendation_reason: '可用 Metasploit 模块意味着武器化门槛极低；FortiManager 通常暴露于管理网络但也存在 internet-facing 实例。',
      trend_signal: 'growing', action_suggestion: '内部 ASM 立即扫描 FortiManager 7.4 系列设备，确认是否暴露于公网；优先 patch 至 7.4.5+。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
    },
    {
      id: 'ai_arxiv:2605.14210', source_id: 'ai_arxiv', domain: 'ai',
      title: 'Test-time Scaling Laws for Mixture-of-Experts Reasoning Models',
      canonical_url: 'https://arxiv.org/abs/2605.14210',
      author: 'Liu et al. (DeepSeek-AI, Tsinghua)', published_at: ago(720), fetched_at: ago(36),
      also_seen_in: [seen('ai_hackernews', 40, 'https://news.ycombinator.com/item?id=39812777')],
      category: 'research', tags: ['llm', 'moe', 'reasoning', 'scaling-laws', 'test-time'],
      summary_zh: '提出一组针对 MoE 推理模型的 test-time scaling laws，发现在 1B–671B 活跃参数区间，最优推理预算与 expert 路由熵呈对数关系，挑战了 dense 模型的简单 chain-length scaling 假说。',
      insight_score: 86, credibility: 'high',
      confidence: 'firm',
      recommendation_reason: 'DeepSeek 团队对 MoE 在 test-time compute 上的系统性研究，与近期 R1/R2 工作可直接对照；论文在 HN 已登顶。',
      trend_signal: 'growing', action_suggestion: '若在内部部署 MoE 模型用于推理任务，可参考论文的 router-entropy 调度策略调整 sampling budget。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
    },
    {
      id: 'ai_openai_blog:gpt5-turbo-realtime', source_id: 'ai_openai_blog', domain: 'ai',
      title: 'Introducing GPT-5 Turbo Realtime: 200ms latency speech-to-speech with tool calling',
      canonical_url: 'https://openai.com/blog/gpt-5-turbo-realtime',
      author: 'OpenAI', published_at: ago(180), fetched_at: ago(36),
      also_seen_in: [
        seen('ai_hackernews', 39, 'https://news.ycombinator.com/item?id=39812888'),
        seen('ai_aihot', 38, 'http://127.0.0.1:18220/post/9201'),
      ],
      category: 'product', tags: ['openai', 'gpt5', 'realtime', 'voice', 'multimodal'],
      summary_zh: 'OpenAI 发布 GPT-5 Turbo Realtime，端到端语音延迟降至 200ms 量级，支持工具调用、function calling 与多 agent 协同，定价为旧 realtime 模型的 40%。',
      insight_score: 78, credibility: 'high',
      confidence: 'confirmed',
      recommendation_reason: '官方一手发布、HN 与 aihot 同步报道；价格与延迟双降意味着语音 agent 产品形态门槛进一步降低。',
      trend_signal: 'emerging', action_suggestion: '评估现有语音相关产品线是否值得迁移；关注国内开源生态对 200ms 语音 stack 的对标速度。',
      analysis_stage: 2,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(37),
      stage2_model: 'deepseek-ai/deepseek-v4-pro', stage2_provider: 'nvidia', stage2_prompt_version: 's2_v1', stage2_analyzed_at: ago(35),
    },
    {
      id: 'ai_hackernews:39812441', source_id: 'ai_hackernews', domain: 'ai',
      title: 'Show HN: Local-first RAG with SQLite vector ext, 12k QPS on M3 Max',
      canonical_url: 'https://news.ycombinator.com/item?id=39812441',
      author: 'kyle-hn', published_at: ago(300), fetched_at: ago(36),
      also_seen_in: [],
      category: 'tool', tags: ['rag', 'sqlite', 'local-first', 'vector'],
      summary_zh: '开发者发布 SQLite vector 扩展实现的 local-first RAG 框架，在 M3 Max 上对 1M 文档跑出 12k QPS 查询；评论区讨论 ANN 召回精度与 schema 设计取舍。',
      insight_score: 68, credibility: 'medium',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'security_nvd_cve:CVE-2026-30188', source_id: 'security_nvd_cve', domain: 'security',
      title: 'CVE-2026-30188: Authentication bypass in Atlassian Confluence Data Center',
      canonical_url: 'https://nvd.nist.gov/vuln/detail/CVE-2026-30188',
      author: 'NVD', published_at: ago(500), fetched_at: ago(38),
      also_seen_in: [],
      category: 'vulnerability', tags: ['cve', 'atlassian', 'confluence', 'auth-bypass'],
      summary_zh: 'Confluence Data Center 8.0–8.5 存在认证绕过，未授权用户可读取受限页面。CVSS 6.5，已发布补丁 8.5.4。',
      insight_score: 64, credibility: 'high',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
      cve_id: 'CVE-2026-30188', cvss: 6.5, cvss_vector: 'AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    },
    {
      id: 'security_sechub:in-22841', source_id: 'security_sechub', domain: 'security',
      title: 'SecHub Weekly Threat Brief — 2026-W21 Ransomware operations targeting Asian MSPs',
      canonical_url: 'http://127.0.0.1:18210/post/22841',
      author: 'SecHub', published_at: ago(900), fetched_at: ago(37),
      also_seen_in: [],
      category: 'incident', tags: ['ransomware', 'msp', 'apac', 'threat-intel'],
      summary_zh: '内部威胁简报：本周观测到至少三起针对亚太地区 MSP 的勒索软件入侵事件，使用变种 BlackSuit。提供 IOC 列表与 detection 规则建议。',
      insight_score: 71, credibility: 'high',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'ai_aihot:9201', source_id: 'ai_aihot', domain: 'ai',
      title: 'Anthropic 推出 Claude Code Spaces：多文件多 agent 协作沙盒',
      canonical_url: 'http://127.0.0.1:18220/post/9201',
      author: 'aihot', published_at: ago(380), fetched_at: ago(36),
      also_seen_in: [seen('ai_hackernews', 33, 'https://news.ycombinator.com/item?id=39812999')],
      category: 'product', tags: ['anthropic', 'claude-code', 'agents'],
      summary_zh: 'Anthropic 发布 Claude Code Spaces，将多 agent 工作流封装为可共享的沙盒会话，支持检查点、回放与文件流。HN 评论关注的是计费模式。',
      insight_score: 67, credibility: 'medium',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'security_github_advisories:GHSA-8wmh-rvxc-2222', source_id: 'security_github_advisories', domain: 'security',
      title: 'GHSA-8wmh-rvxc-2222: Path traversal in axios FormData adapter',
      canonical_url: 'https://github.com/advisories/GHSA-8wmh-rvxc-2222',
      author: 'GitHub Security Lab', published_at: ago(620), fetched_at: ago(38),
      also_seen_in: [],
      category: 'vulnerability', tags: ['ghsa', 'axios', 'path-traversal', 'nodejs'],
      summary_zh: 'axios 1.7.0–1.7.7 在 FormData adapter 处理文件名时未规范化路径，攻击者可通过 ../ 写入任意位置。修复版本 1.7.8。',
      insight_score: 58, credibility: 'high',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'ai_arxiv:2605.14188', source_id: 'ai_arxiv', domain: 'ai',
      title: 'Differential Privacy for Long-Context Embedding Models: A Practical Analysis',
      canonical_url: 'https://arxiv.org/abs/2605.14188',
      author: 'Chen et al. (CMU)', published_at: ago(820), fetched_at: ago(36),
      also_seen_in: [],
      category: 'research', tags: ['llm', 'privacy', 'embeddings', 'dp'],
      summary_zh: '对 long-context embedding 模型实施差分隐私的实证分析，提出 token-level DP-SGD 变体在 32K 上下文下 utility 损失低于 3%。',
      insight_score: 55, credibility: 'high',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'ai_hackernews:39812502', source_id: 'ai_hackernews', domain: 'ai',
      title: 'Why we moved off LangChain after 18 months in production',
      canonical_url: 'https://news.ycombinator.com/item?id=39812502',
      author: 'eng-blog-hn', published_at: ago(700), fetched_at: ago(36),
      also_seen_in: [],
      category: 'engineering', tags: ['langchain', 'postmortem', 'production'],
      summary_zh: '某公司技术博客复盘其从 LangChain 迁移到自研 agent 框架的 18 个月经验，关注抽象漏出、调试成本与版本破坏性更新。',
      insight_score: 49, credibility: 'medium',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'security_exploitdb:52887', source_id: 'security_exploitdb', domain: 'security',
      title: 'WordPress Plugin Booking-Calendar 9.2.1 — SQLi (Authenticated Subscriber)',
      canonical_url: 'https://www.exploit-db.com/exploits/52887',
      author: 'spencerm', published_at: ago(1020), fetched_at: ago(38),
      also_seen_in: [],
      category: 'exploit', tags: ['wordpress', 'plugin', 'sqli'],
      summary_zh: 'WordPress Booking-Calendar 插件 9.2.1 之前版本存在已认证 SQL 注入，需 subscriber 权限。',
      insight_score: 42, credibility: 'medium',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'ai_aihot:9197', source_id: 'ai_aihot', domain: 'ai',
      title: 'Mistral Small 3.5 发布：22B dense，单卡 4090 可跑',
      canonical_url: 'http://127.0.0.1:18220/post/9197',
      author: 'aihot', published_at: ago(900), fetched_at: ago(36),
      also_seen_in: [],
      category: 'product', tags: ['mistral', 'opensource', 'local-llm'],
      summary_zh: 'Mistral Small 3.5 在 22B dense 架构下达成 70B 级 benchmark；Apache 2.0 许可，单卡 24GB 显存可推理。',
      insight_score: 47, credibility: 'medium',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
    {
      id: 'security_nvd_cve:CVE-2026-30041', source_id: 'security_nvd_cve', domain: 'security',
      title: 'CVE-2026-30041: XSS in Jenkins LDAP plugin admin console',
      canonical_url: 'https://nvd.nist.gov/vuln/detail/CVE-2026-30041',
      author: 'NVD', published_at: ago(1200), fetched_at: ago(38),
      also_seen_in: [],
      category: 'vulnerability', tags: ['cve', 'jenkins', 'xss'],
      summary_zh: 'Jenkins LDAP 插件管理控制台存在反射 XSS，需要管理员权限触发。CVSS 4.8。',
      insight_score: 32, credibility: 'high',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
      cve_id: 'CVE-2026-30041', cvss: 4.8,
    },
    {
      id: 'ai_hackernews:39812355', source_id: 'ai_hackernews', domain: 'ai',
      title: 'Ask HN: What is your team\'s 2026 LLM observability stack?',
      canonical_url: 'https://news.ycombinator.com/item?id=39812355',
      author: 'observability-curious', published_at: ago(1340), fetched_at: ago(36),
      also_seen_in: [],
      category: 'discussion', tags: ['observability', 'llm', 'community'],
      summary_zh: 'HN 讨论：2026 年 LLM observability 栈调查。评论中频繁提及 Langfuse、Helicone 与自建 OpenTelemetry 方案。',
      insight_score: 24, credibility: 'low',
      analysis_stage: 1,
      stage1_model: 'deepseek-ai/deepseek-v4-flash', stage1_provider: 'nvidia', stage1_prompt_version: 's1_v1', stage1_analyzed_at: ago(29),
    },
  ];

  /* ---------- runs ---------- */
  const runs = [
    {
      id: 'run_20260526_000000', kind: 'daily', status: 'running',
      window_start: ago(60 * 24 + 14), window_end: ago(14), started_at: ago(38),
      finished_at: null,
      stats: {
        sources: {
          security_nvd_cve: { status: 'succeeded', items: 18, duration_s: 3.2 },
          security_github_advisories: { status: 'succeeded', items: 7, duration_s: 5.4 },
          security_portswigger: { status: 'failed', error: 'source_timeout', duration_s: 30.0 },
          security_project_zero: { status: 'succeeded', items: 1, duration_s: 1.8 },
          security_exploitdb: { status: 'succeeded', items: 5, duration_s: 2.7 },
          security_sechub: { status: 'succeeded', items: 4, duration_s: 0.9 },
          ai_aihot: { status: 'succeeded', items: 12, duration_s: 1.1 },
          ai_hackernews: { status: 'succeeded', items: 9, duration_s: 4.6 },
          ai_arxiv: { status: 'succeeded', items: 6, duration_s: 6.1 },
          ai_openai_blog: { status: 'succeeded', items: 1, duration_s: 1.3 },
        },
        stage1: { total: 63, succeeded: 61, failed: 2 },
        stage2: { total: 9, running: 3, succeeded: 6, failed: 0 },
        dedup_skipped: 8,
        retention_deleted: 0,
      },
      progress: 0.78,
    },
    {
      id: 'run_20260525_000000', kind: 'daily', status: 'partial',
      window_start: ago(60 * 48), window_end: ago(60 * 24 + 14), started_at: ago(60 * 24 + 14),
      finished_at: ago(60 * 24 - 320),
      stats: {
        sources: {
          security_nvd_cve: { status: 'succeeded', items: 14, duration_s: 3.0 },
          security_github_advisories: { status: 'succeeded', items: 6, duration_s: 5.1 },
          security_portswigger: { status: 'succeeded', items: 2, duration_s: 8.4 },
          security_project_zero: { status: 'succeeded', items: 0, duration_s: 1.5 },
          security_exploitdb: { status: 'succeeded', items: 4, duration_s: 2.5 },
          security_sechub: { status: 'succeeded', items: 3, duration_s: 0.8 },
          ai_aihot: { status: 'succeeded', items: 11, duration_s: 1.0 },
          ai_hackernews: { status: 'succeeded', items: 7, duration_s: 4.3 },
          ai_arxiv: { status: 'failed', error: 'source_parse_error', duration_s: 12.7 },
          ai_openai_blog: { status: 'succeeded', items: 1, duration_s: 1.4 },
        },
        stage1: { total: 48, succeeded: 47, failed: 1 },
        stage2: { total: 7, succeeded: 7, failed: 0 },
        dedup_skipped: 6,
        retention_deleted: 5,
      },
      progress: 1,
    },
    {
      id: 'run_20260524_000000', kind: 'daily', status: 'succeeded',
      window_start: ago(60 * 72), window_end: ago(60 * 48),
      started_at: ago(60 * 48), finished_at: ago(60 * 48 - 410),
      stats: {
        sources: {
          security_nvd_cve: { status: 'succeeded', items: 11, duration_s: 3.4 },
          security_github_advisories: { status: 'succeeded', items: 4, duration_s: 4.9 },
          security_portswigger: { status: 'succeeded', items: 1, duration_s: 6.3 },
          security_project_zero: { status: 'succeeded', items: 0, duration_s: 1.4 },
          security_exploitdb: { status: 'succeeded', items: 8, duration_s: 3.1 },
          security_sechub: { status: 'succeeded', items: 5, duration_s: 0.9 },
          ai_aihot: { status: 'succeeded', items: 9, duration_s: 1.2 },
          ai_hackernews: { status: 'succeeded', items: 11, duration_s: 4.4 },
          ai_arxiv: { status: 'succeeded', items: 5, duration_s: 7.0 },
          ai_openai_blog: { status: 'succeeded', items: 0, duration_s: 1.3 },
        },
        stage1: { total: 54, succeeded: 54, failed: 0 },
        stage2: { total: 8, succeeded: 8, failed: 0 },
        dedup_skipped: 4, retention_deleted: 7,
      },
      progress: 1,
    },
    {
      id: 'run_20260523_142200', kind: 'manual', status: 'succeeded',
      window_start: ago(60 * 90), window_end: ago(60 * 90 - 60),
      started_at: ago(60 * 90), finished_at: ago(60 * 90 - 380),
      stats: {
        sources: {},
        stage1: { total: 12, succeeded: 12, failed: 0 },
        stage2: { total: 2, succeeded: 2, failed: 0 },
        dedup_skipped: 1, retention_deleted: 0,
      },
      progress: 1,
    },
  ];

  /* ---------- digest ---------- */
  const digest = {
    id: '2026-05-26:security', date: '2026-05-26', domain: 'security',
    title: '安全情报日报 · 2026-05-26',
    overview: '今日共采集 35 条原始安全情报，AI 分析后高价值（≥75）item 共 4 条，覆盖 Linux 内核 io_uring 提权、Project Zero 对 MTE 的深度研究、next-auth 反序列化 RCE 与 FortiManager 预认证溢出。建议立即处理 io_uring 与 FortiManager 两项；其余条目可纳入本周复盘。',
    stats: { collected: 35, analyzed: 35, high_value: 4, failed_sources: 1 },
    highlights_json: [
      {
        name: 'vulnerability', label: '漏洞披露', count: 2,
        item_ids: ['security_nvd_cve:CVE-2026-31415', 'security_github_advisories:GHSA-7q4f-pgqx-h3vh'],
      },
      {
        name: 'exploit', label: '武器化 / PoC', count: 1,
        item_ids: ['security_exploitdb:52891'],
      },
      {
        name: 'research', label: '深度研究', count: 1,
        item_ids: ['security_project_zero:1842'],
      },
    ],
    hexo_path: 'intelligence-security-2026-05-26.md',
    oss_url: 'https://suuuuzsk.oss-cn-guangzhou.aliyuncs.com/intelligence/digests/2026-05-26/security.md',
    generated_at: ago(8),
    categories: [
      {
        name: 'vulnerability', label: '漏洞披露', count: 2,
        item_ids: ['security_nvd_cve:CVE-2026-31415', 'security_github_advisories:GHSA-7q4f-pgqx-h3vh'],
      },
      {
        name: 'exploit', label: '武器化 / PoC', count: 1,
        item_ids: ['security_exploitdb:52891'],
      },
      {
        name: 'research', label: '深度研究', count: 1,
        item_ids: ['security_project_zero:1842'],
      },
    ],
  };

  return { now, sources, items, runs, digest };
})();

export const byId = (arr, id) => arr.find(x => x.id === id);
